# Generated by Django 3.2.9 on 2021-11-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211117_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out  for delivery', 'out for delivery'), ('delivered', 'delivery')], max_length=200),
        ),
    ]
